name: interactivenotebooks
channels:
  - defaults
  - omnia
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - bokeh=2.0.2
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - plotly=4.6.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - retrying=1.3.3
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.4.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
prefix: /home/cbarnett/anaconda3/envs/interactivenotebooks
